name: CI

on:
  - push
  - pull_request

env:
  SHELL: /bin/zsh

jobs:
  all:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Install some necessary programs
        run: |
          sudo apt install -y zsh
      - name: Install sane-fmt
        uses: sane-fmt/action@0.16.0
        with:
          run: 'false'
          export-path: 'true'
      - name: Cache
        timeout-minutes: 1
        continue-on-error: true
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('**/deps.ts') }}
          restore-keys: |
            deno-${{ runner.os }}-${{ hashFiles('**/deps.ts') }}
            deno-${{ runner.os }}-
            deno-
      - name: Install Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: 1.9.1
      - name: Run all targets in Drakefile
        run: |
          deno run --allow-all --unstable Drakefile.ts all
      - name: Prepare for uploading deno cache as artifacts
        run: |
          cp -r ~/.cache/deno deno-cache.tmp
      - name: Upload deno cache as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deno-cache
          path: deno-cache.tmp

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sane-fmt/action@0.16.0
        with:
          args: |
            - --details=diff
            - --color=always
            - .
